### ISSUE TITLE
Spelling mistake

### ISSUE THREAD

**Issue by supcik** [GDGFribourg/hello-world#1]
**Describe the bug**

There is a spelling mistake in the text

**To Reproduce**
1. Run the program and read the output
  
**Expected behavior**
"Helo" seems mispelled. I guess "Hello" would be better

**Screenshots**
not applicable

**Desktop (please complete the following information):**
 - OS: MacOS

**Smartphone (please complete the following information):**
not applicable

**Additional context**
not applicable

**Comment by derlin** [comment]
I would be interested in this one.
